### ISSUE TITLE
Add WUP Name to Search Options

### ISSUE THREAD

**Issue by SarahNWF** [NWFWMD-IT/Wells#12]
Add WUP Name as an option for searching Surface Water Withdrawl

**Comment by john-beamish** [comment]
> Add WUP Name as an option for searching Surface Water Withdrawl

This is already enabled :)  

I'll work on:

> In the search widget you can select what fields are used as the labels in the drop down list. For example when you search a parcel you'll see all of the options say "FL". We should probably tidy up all the options in the search widgets.
