### ISSUE TITLE
Remove Last Calibration Field

### ISSUE THREAD

**Issue by SarahNWF** [NWFWMD-IT/Wells#15]
Remove Last Calibration signifier/field

**Comment by SarahNWF** [comment]
Do they want it out of the database completely? We could always hide it in the field maps form and leave it for WUP staff in office to fill out.

**Comment by john-beamish** [comment]
> Do they want it out of the database completely? We could always hide it in the field maps form and leave it for WUP staff in office to fill out.

I think they just didn't want it in the WUP Site map, I'll just hide that field in the web map.
