### ISSUE TITLE
Comments Field Character Length

### ISSUE THREAD

**Issue by SarahNWF** [NWFWMD-IT/Wells#4]
Make sure comments field has enough character length and also look into making the comments box field bigger so users feel like they have enough room to type a lengthy comment if need by.  Right now the small box makes it look like you only have a little space for comments, even if the character limit is actually high.

**Comment by SarahNWF** [comment]
I'm not sure if we can changed the actual dimensions of the comments box. We'll just have to make sure it's known what the character limit is. Right now it's 255, the default. We should be able to increase the size. If we can't, we can create a new column with an increased limit and copy the data from the old column to the new column.

**Comment by john-beamish** [comment]
> I'm not sure if we can changed the actual dimensions of the comments box. We'll just have to make sure it's known what the character limit is. Right now it's 255, the default. We should be able to increase the size. If we can't, we can create a new column with an increased limit and copy the data from the old column to the new column.

Wasn't able to increase the comment length, I'll make a new column and copy the data over.
