### ISSUE TITLE
WUP Facility Name Label for WUP Project Sites

### ISSUE THREAD

**Issue by SarahNWF** [NWFWMD-IT/Wells#5]
For Well Withdrawl, Well Injection, Surface Water Withdrawl, & Surface Water Discharge, show WUP Facility Name as label when zoomed in to project level (leave option to toggle on off, have on as default.  This seemed more important than showing parcel numbers so this labeling should be the default instead of that.

**Comment by john-beamish** [comment]
Done, however some of the basemap labels draw over these labels which looks bad.  

Possible solutions are 

1. A custom basemap where we can directly control the layer order of the labels

2. Building a custom web application using ArcGIS API for JavaScript and use code to reorder the layers

Both these options would take a bit of time, unless somebody complains about this it's not worth the time right now IMO
