### ISSUE TITLE
WUP Station Symbology

### ISSUE THREAD

**Issue by SarahNWF** [NWFWMD-IT/Wells#6]
Make WUP Station color change based on status.  Tom wanted Active = blue, Inactive = Yellow, & Abandoned = Red (we can change these colors if they don't make sense.  Blue might be confusing because there's already a lot of blue symbology, idk.)

**Comment by SarahNWF** [comment]
Keep in mind Tom is color blind - use colors that are easy for him to distinguish. Does he want us to change the WUP station symbology or the project points? I know they asked me to change the colors of the project points in the past. (project points being well withdraw, surface water withdraw, the ones we're managing)

**Comment by john-beamish** [comment]
This is finished in mw separate ArcPro project but not applied to the actual service or web map, I can update the service with these symbology edits whenever we want to try it out and the original symbology is saved in the reg services project if/when we want to revert back.

**Comment by john-beamish** [comment]
Ok, I made the changes in a copy of the web map.
