### ISSUE TITLE
County Roads Symbology

### ISSUE THREAD

**Issue by SarahNWF** [NWFWMD-IT/Wells#8]
Digits in the white box symbology for County Roads are off center.

**Comment by SarahNWF** [comment]
From Esri basemap or from our own symbology?

**Comment by john-beamish** [comment]
> From Esri basemap or from our own symbology?

Yeah, this is from the ESRI basemap.  I just looked again and the 3 digit county road numbers do look a pixel or two off center to the right within the white box.  

It doesn't matter at all lol, I just thought we might as well fix it if it were our own symbology, but since it's not it's fine.
